#!/bin/bash
set -e

FWPATH="../"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#################### HW 410 & 411 & 412 ########################

COPYDIR=410_o_411_o_412
rm $COPYDIR/* || true

# default
cd $FWPATH
touch conf_general.h
make -j8 build_args="-DHW_VERSION_410"
cd $DIR
cp $FWPATH/build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin
